services:
  landing:
    image: landing_001k
    container_name: landing_001k
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - web

  caddy:
    image: caddy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    depends_on:
      - landing
    restart: unless-stopped
    networks:
      - web

volumes:
  caddy_data:

networks:
  web:
# services:
#   landing:
#     build:
#       context: .
#       target: development
#     container_name: landing_course
#     ports:
#       - "3000:3000"
#     volumes:
#       - .:/app
#       - /app/node_modules
#     environment:
#       - NODE_ENV=development