services:
  landing:
    build:
      context: .
      target: runner
    container_name: landing_001k
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

# services:
#   landing:
#     build:
#       context: .
#       target: development
#     container_name: landing_course
#     ports:
#       - "3000:3000"
#     volumes:
#       - .:/app
#       - /app/node_modules
#     environment:
#       - NODE_ENV=development